### ISSUE TITLE
BERT Large , 512 sequence length - Allocation of X exceeds Y% of system memory.

### ISSUE THREAD

**Issue by 17patelumang** [google-research/bert#1030]
Hi ,

I am trying to run BERT Large model having 512 sequence length on CPU for inference. I have converted checkpoint file from BERT Large to savedModel format which has feature transformation ported to it as well.

However when I do the inference I can see  warning message as 

**"tensorflow/core/framework/cpu_allocator_impl.cc:81] Allocation of X exceeds 10% of system memory."**

Could anyone please help me identifying the root cause. Having read different issue related to this it says that the batch size needs to be reduced however trying that doesn't help.

**Comment by MarwahAhmadHelaly** [comment]
Hello, 

There are several reasons that could cause this:
1) The BERT Large model is very high in computation and memory needs, as noted in the ReadMe. Seeing that you are running on CPU, I think that may cause some issues.

2) The amount of self-attention performed is quadratic to the maximum sequence length you selected, which is 512. I suggest trying a smaller max_seq_len.

3) batch_size when decreased also reduces the amount of memory needed, what batch_size did you use?

Kindly take a look here: https://github.com/google-research/bert#out-of-memory-issues

**Comment by 17patelumang** [comment]
@MarwahAhmadHelaly thank you reply .  Could you please share more details on how "amount of self-attention performed is quadratic to the maximum sequence length you selected" ?

**Comment by 17patelumang** [comment]
We have tried 2 and 3

**Comment by MarwahAhmadHelaly** [comment]
> @MarwahAhmadHelaly thank you reply . Could you please share more details on how "amount of self-attention performed is quadratic to the maximum sequence length you selected" ?

As mentioned here: https://github.com/google-research/bert#pre-training-tips-and-caveats, point # 5

"Longer sequences are disproportionately expensive because attention is quadratic to the sequence length. In other words, a batch of 64 sequences of length 512 is much more expensive than a batch of 256 sequences of length 128. The fully-connected/convolutional cost is the same, but the attention cost is far greater for the 512-length sequences. Therefore, one good recipe is to pre-train for, say, 90,000 steps with a sequence length of 128 and then for 10,000 additional steps with a sequence length of 512. The very long sequences are mostly needed to learn positional embeddings, which can be learned fairly quickly. Note that this does require generating the data twice with different values of max_seq_length."


> We have tried 2 and 3

You reached a batch_size of 1 or 2? If you are still facing problems after point 2 and 3, I believe your best option may be:
1) change to the Base model, if this can serve the purpose you are looking for, or
2) if you still need the Large model, I think you need to look for more powerful resources (GPU/TPUs and memory)
3) try changing the default Adam optimizer but with a possible cost, as mentioned here: https://github.com/google-research/bert#out-of-memory-issues

**Comment by 17patelumang** [comment]
@MarwahAhmadHelaly  thank you

**Comment by MarwahAhmadHelaly** [comment]
You're welcome, all the best

**Comment by 17patelumang** [comment]
@MarwahAhmadHelaly  whats the average latency i should expect on CPU ?
