### ISSUE TITLE
why all  the next_sentence_labels equal 1 with run create_pretraining_data.py?

### ISSUE THREAD

**Issue by zepen** [google-research/bert#125]
![image](https://user-images.githubusercontent.com/18568380/48550277-47029b80-e90d-11e8-8b12-8c819540405e.png)
![image](https://user-images.githubusercontent.com/18568380/48550304-5550b780-e90d-11e8-9949-b7ddab28f819.png)
i understander wrong?

**Comment by jacobdevlin-google** [comment]
"1" actually means "is random" because that's the convention I used originally. The problem is that there are blank lines between your input sentences so the system thinks that each its its own document, and next sentence can't cross documents. So just remove the empty line between segments in the same document.

**Comment by zepen** [comment]
thanks a lot
