### ISSUE TITLE
apply bert as basic encoder to intergate with classificial architecture, but achieve worse result than original finetuning

### ISSUE THREAD

**Issue by yyht** [google-research/bert#142]
I had tried to apply bert as a basic sentence encoder, and stacked on some traditional architecture such as match pyramid, question and passage interaction for downstream task such as nli, qa. But I got worse results compared to originial fintuing. And it took more time to converge than original finetuning...

**Comment by hanxiao** [comment]
for using BERT as a sentence encoder, maybe you want to check https://github.com/hanxiao/bert-as-service

**Comment by jacobdevlin-google** [comment]
BERT is not designed to be a "sentence encoder". If you used the hidden vector corresponding to the `[CLS]` token as a fixed representation that is certainly bad, because that is not a meaningful representation of the sentence. 

Our recommended method of using BERT for classification is fine-tuning, as shown in `run_classifier.py`. If you want to use BERT for with features, we would recommend some sort of learned pooling over the word tokens, but we don't have a specific recommendation for how to do this since this was not really the focus of the paper.
