### ISSUE TITLE
pertained Chinese language model request, please.

### ISSUE THREAD

**Issue by Jorigorn** [google-research/bert#2]
It would be very nice you can release the some other language models, like German, Chinese etc. Then we can experiment them on other language domains. 

Thanks a lot. :)
John.

**Comment by rico93** [comment]
We have the similar request, because we didn't have enough computing power to train a model. If u can  provide the Chinese pretrained model that will be very helpful.  Thanks for your time and help.

Best Wishes
Rico

**Comment by kuni-kuni** [comment]
Also please Japanese version.
It would break the barrier.

Thanks

**Comment by hauturier** [comment]
Both simplified and traditional Chinese, please.

**Comment by KevinChen1994** [comment]
China's developer need Chinese pretrained model badly.
Thanks a lot!

**Comment by chendengshuai** [comment]
very excepting

**Comment by jacobdevlin-google** [comment]
I am in the process of training models on the [top 60 languages which have the largest Wikipedias](https://meta.wikimedia.org/wiki/List_of_Wikipedias). This contains both simplified and traditional Chinese, Korean, Japanese, German, Spanish, and many others. I will likely release a single BERT-Base and BERT-Large models trained on all of these languages (including English). Hopefully this will be released within the next few weeks, but I have to actually test it and make sure it works reasonably well.

To handle the spacing issue in Chinese, we simply character-tokenize any characters in the CJK Unicode set, and perform our same recipe for everything else. There is one big shared 100k WordPiece vocabulary. This recipe seems to work well for *almost* all languages (unfortunately, the one exception is Thai, since there are few spaces but too many characters-per-word to use character tokenization).

**Comment by jacobdevlin-google** [comment]
If I re-generate the data (which looks likely at this point to better weight the low-resource languages) then I'll try to include more from the 60-100 range.

**Comment by yunjiangster** [comment]
Will the large Chinese model be released any time soon? Thanks for the hard work by the way.

**Comment by ShenDezhou** [comment]
Hi，friends，I have pretrained a Chinese language BERT model. https://github.com/ShenDezhou/Chinese-PreTrained-BERT . If you would accept it，I might request a PR.
