### ISSUE TITLE
Could tensor2tensor support bert?

### ISSUE THREAD

**Issue by daiwk** [google-research/bert#3]
Could this official repository https://github.com/tensorflow/tensor2tensor support bert?

**Comment by loretoparisi** [comment]
My 2 cents is the rule "keep it simple" like _fastText_. You get a binary all-in-one solution, no framework, ELF file compiled from C++, static linked, anything else. No boost library, no tensorflow, no tensor2tensor. This is a win-win solution. I beat for that.

**Comment by jacobdevlin-google** [comment]
tensor2tensor is a great library but has more layers of abstraction than what we want for BERT. BERT is designed to be very lightweight and standalone with minimal abstraction (the core library is 3 files: `modeling.py`, `tokenization.py`, and `optimziation.py`, with no dependencies and simple APIs for using each).

**Comment by loretoparisi** [comment]
@jacobdevlin-google I love this approach, very close to my initial idea!!! Thanks a lot!

**Comment by stefan-falk** [comment]
Please, somebody correct me if I am wrong, shouldn't BERT be possible with tensor2tensor since its core is a [`Transformer`](https://github.com/tensorflow/tensor2tensor/blob/v1.14.0/tensor2tensor/models/transformer.py) model?

From [bert](https://github.com/google-research/bert):
> We then train a large model (12-layer to 24-layer Transformer) on a large corpus (Wikipedia + BookCorpus) for a long time (1M update steps), and that's BERT.

Shouldn't it be enough to "_just_" create a dataset accordingly and start a training with that?
