### ISSUE TITLE
why need to change words to "###*"by apply tokenization?

### ISSUE THREAD

**Issue by waallf** [google-research/bert#44]
Hi,I couldn't understand  why need to change words to "###*" by apply tokenization.
 `E.g., john johanson ' s , → john johan ##son ' s ,`

**Comment by guotong1988** [comment]
THX

**Comment by telukuntla** [comment]
Hi, why do we need to split rare words in to sub words. also please explain WordPiece tokenization in the context of BERT.

**Comment by JayMody** [comment]
> Hi, why do we need to split rare words in to sub words. also please explain how WordPiece tokenization is useful in the context of BERT.

The idea is you can reduce the size of your vocabulary. For example, run, running, runner are all very similar words. Without wordpiece you would need to store and learn the meaning of all three independently.

With wordpiece, each of the three words would be split into 'run' and the related '##SUFFIX' (if any suffix at all). So the context of all three words would intermingle, which makes sense, since they are all similar words. The rest of the meaning would be encoded in the suffix, which would be learning from other words with similar suffixes. 

The benefit is that you will have a reduced vocab size and makes for better training.
