### ISSUE TITLE
How to fine tune bert on small labeled twitter dataset?

### ISSUE THREAD

**Issue by RoderickGu** [google-research/bert#842]
Most people test bert on large dataset, but when it comes to small dataset, I assume the fine tune process and batch size maybe different. Besides, the dataset domain is twitter domain, which is kind of different from BERT pretrained corpus.
Could anyone gives some suggestions on finetuning BERT on small labeled twitter dataset? Thanks in advance for any help.

**Comment by yslin1995** [comment]
I have the same question about fine-tuning, have you come up with any solutions? 

Moreover, due to the next-sentence-prediction pretraining task(requiring documents or coherent sentences), we may not even construct such task for training bert on twitter domain from scratch(since each tweet is independent)

**Comment by g-jing** [comment]
> I have the same question about fine-tuning, have you come up with any solutions?
> 
> Moreover, due to the next-sentence-prediction pretraining task(requiring documents or coherent sentences), we may not even construct such task for training bert on twitter domain from scratch(since each tweet is independent)

You could use twitter of long text to do NSP. However, NSP has been proven not so useful(even deficient). I suggest: 1 transfer learning. 2. small batch size and large lr if training data is small. Try roberta, alberta instead of BERT.
