### ISSUE TITLE
It took a several days to create pretraining data and hasn't finished.

### ISSUE THREAD

**Issue by yyht** [google-research/bert#89]
I planned to pre-train bert on my own dataset( 130M finicial news , 3.3GB, Chinese) for event extraction and sentiment detection. I had applied sentence piece model from google to build my own vocabluary and tokenization the whole dataset. However, it already took two days but still couldn't generate related tfrecords.

![image](https://user-images.githubusercontent.com/14133687/48240177-ca535700-e40c-11e8-995d-8dc312751eae.png)

**Comment by Colanim** [comment]
Are you running it on GPU ?

**Comment by IntelOSt** [comment]
no ilike



Sent from my Redmi 4A
On Colanim <notifications@github.com>, Nov 9, 2018 11:19 AM wrote:

Are you running it on GPU ?

**Comment by yyht** [comment]
just use create_pretraining_data.py with sentence piece for tokenization on CPU to create tfrecords. It worded for small dataset...

**Comment by jacobdevlin-google** [comment]
I mention this in the README, but for large files I would recommend splitting the file into a number of smaller chunks and then calling `create_pretraining_data` for each chunk, because the memory use can be very large for large files. So you could generate tf_examples.tfrecord_000, tf_examples.tf_record_001, ... and then you can pass in a glob like `tf_examples.tfrecord*` to `run_pretraining.py`.
