### ISSUE TITLE
BERT Multi-lingual: similarity score of two different languages?

### ISSUE THREAD

**Issue by chiragsanghvi10** [google-research/bert#967]
Hi,

Is it possible to find the similarity score of two different languages?

### For example:
> Sentence 1 (English) 
> Sentence 2 (Translation in Hindi of sentence 1)
> Sentence similarity score.

Best
Chirag Sanghvi

**Comment by real-brilliant** [comment]
i've tried multilingual machine translation based on transformer, embedding from different language will cluster on different clusters, and distance between these clusters is concerned with similarities between languages.

i think it will be the same in this case, similarity will only meaningful when relative similarity is measured

**Comment by chiragsanghvi10** [comment]
Hi @real-brilliant ,
I am trying multilingual machine translation as well, But how did you fine-tune the multi-lingual model?
And what kind of data?
Can you share the code?

**Comment by real-brilliant** [comment]
I tried that based on tensor2tensor instead of bert.

As for fine-tuning data, i use 1:1 multilingual data between each language pairs.
Although google's team claims that using as much data as you have will greatly improve bleu of low-resource language, training based on  even-distributed data is a more safe choice, and will greatly prevent the recurrence of wrong language in decoding

Codes is not private and cannot be shared, sorry for that.

**Comment by chiragsanghvi10** [comment]
Hi @real-brilliant ,
I am trying the same thing, i am using 1:1 multilingual data between each language pairs. 
I understand that's OK.
Thank you for your response.

Best,
Chirag Sanghvi

**Comment by bittlingmayer** [comment]
Have a look at [facebookresearch/LASER](https://github.com/facebookresearch/LASER) for some ideas, this is discussed extensively in the issues.
