### ISSUE TITLE
bert run_classifier

### ISSUE THREAD

**Issue by shravanc** [google-research/bert#989]
train_InputExamples = train.apply(lambda x: bert.run_classifier.InputExample(guid=None, # Globally unique ID for bookkeeping, unused in this example
                                                                   text_a = x[DATA_COLUMN],
                                                                   text_b = None,
                                                                   label = x[LABEL_COLUMN]), axis = 1)

I get the below error:
train_InputExamples = train.apply(lambda x: bert.run_classifier.InputExample(guid=None, # Globally unique ID for bookkeeping, unused in this example
AttributeError: ("module 'bert' has no attribute 'run_classifier'", 'occurred at index 17264')

**Comment by danielruss** [comment]
Hi @shravanc,  I came across the same error when I was running the google colab at https://colab.research.google.com/github/google-research/bert/blob/master/predicting_movie_reviews_with_bert_on_tf_hub.ipynb#scrollTo=xiYrZKaHwV81

I think the problem is that run_classifier is in the package "bert-tensorflow" not "bert-for-tf2".  I don't have a work-around for you other than to say try to follow along with the colab.  The InputExample class in in [GitHub](https://github.com/google-research/bert/blob/master/run_classifier.py) on line 127

**Comment by VpkPrasanna** [comment]
i have the same error while i was trying an sample colab notebook as mentioned above but i could not able to find a way to solve it.

**Comment by kaipyroami** [comment]
Still a problem for me on Colab.

**Comment by yagyapandeya** [comment]
The problem solved by updating the TensorFlow in V2.

**Comment by GabrieleAraujo** [comment]
> O problema foi resolvido com a atualização do TensorFlow na V2.

how was it resolved?
